server:
  port: 8090
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: financialdb
      port: 27017
      host: localhost

springdoc:
  swagger-ui:
    disable-swagger-default-url=true:
  packagesToScan: "com.kotlin.financial.entrypoint"